# Generated by Django 5.2.13 on 2026-05-02 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0002_alter_orderupdate_order_id_alter_product_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Client-supplied key; duplicate checkout with same user+key returns existing order.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='orders',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False), ('user__isnull', False)), fields=('user', 'idempotency_key'), name='orders_user_idempotency_key_uniq'),
        ),
    ]
